version: "3"
services:
  awesome-nest-db:
    image: postgres
    container_name: awesome-nest-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - awesome-nest-db-vol:/var/lib/postgresql/data
    env_file:
      - .env
  redis: 
    image: redis:7.2.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - './redis_data:/data'

volumes:
  awesome-nest-db-vol:
    driver: local
  